version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/app
    # networks:
    #   - hoge-network

  client:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./:/usr/src/app
    # networks:
    #   - fuga-network
  
# networks:
#   hoge-network:
#     driver: bridge
  # fuga-network:
  #   driver: bridge